version: '3.8'

services:
  app:
    build: .
    image: kotlin-template-api-service
    container_name: kotlin-template-api-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kotlin-template-api
      - SPRING_DATASOURCE_USERNAME=kotlin-template-api
      - SPRING_DATASOURCE_PASSWORD=kotlin-template-api
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: kotlin-template-api-db
    environment:
      - POSTGRES_DB=kotlin-template-api
      - POSTGRES_USER=kotlin-template-api
      - POSTGRES_PASSWORD=kotlin-template-api
    ports:
      - "5432:5432"

  test:
    build:
      dockerfile: Dockerfile.test
    container_name: kotlin-template-api-service-test
    command: ./gradlew test --info
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kotlin-template-api
      - SPRING_DATASOURCE_USERNAME=kotlin-template-api
      - SPRING_DATASOURCE_PASSWORD=kotlin-template-api
      - CI=true
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - db
