spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/kotlin-template-api"
    username: kotlin_template_api
    password: kotlin_template_api
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
