#!/bin/bash
set -o nounset
set -o errexit

exit_func() {
  docker-compose stop app
}

trap exit_func SIGTERM SIGINT

if [[ "$@" = "--build" ]]
then
  docker-compose build app
fi

echo "Starting the web server..."
docker-compose up --remove-orphans -d app
DOCKER_CONTAINER_ID=$(
  docker ps --filter "name=kotlin-template-api-service" --format "{{.ID}} {{.Names}}" | \
    grep -v run | \
    head -1 | \
    awk '{ print $1 }'
)

echo $DOCKER_CONTAINER_ID

docker logs -f $DOCKER_CONTAINER_ID
