name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run Tests
        run: ./script/test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./shared/jacocoTestReport.xml

  code-check:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Static Analysis
        run: ./gradlew

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, code-check]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Master Docker image
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          bmanley/kotlin-api-template:latest
          bmanley/kotlin-api-template:1.0.${{ github.run_id }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push Dev Docker image
      if: github.ref != 'refs/heads/master'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: bmanley/kotlin-api-template:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
