name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.test
          push: false
          target: test-runner
          tags: bmanley/kotlin-api-template:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push the Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bmanley/kotlin-api-template:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
